// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OfficeNova.Bestelportaal.Data;

#nullable disable

namespace OfficeNova.Bestelportaal.Migrations
{
    [DbContext(typeof(OfficeNovaContext))]
    partial class OfficeNovaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("OfficeNova.Bestelportaal.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Naam = "Muizen"
                        },
                        new
                        {
                            Id = 2,
                            Naam = "Toetsenborden"
                        },
                        new
                        {
                            Id = 3,
                            Naam = "Headsets"
                        },
                        new
                        {
                            Id = 4,
                            Naam = "Ergonomie"
                        },
                        new
                        {
                            Id = 5,
                            Naam = "Laptopstandaards"
                        },
                        new
                        {
                            Id = 6,
                            Naam = "Bureaustoelen"
                        },
                        new
                        {
                            Id = 7,
                            Naam = "Printerinkt"
                        },
                        new
                        {
                            Id = 8,
                            Naam = "Papier"
                        },
                        new
                        {
                            Id = 9,
                            Naam = "Pennen"
                        },
                        new
                        {
                            Id = 10,
                            Naam = "Monitorarmen"
                        },
                        new
                        {
                            Id = 11,
                            Naam = "IT Accessoires"
                        },
                        new
                        {
                            Id = 12,
                            Naam = "Thuiswerkpakketten"
                        },
                        new
                        {
                            Id = 13,
                            Naam = "Facilitair"
                        });
                });

            modelBuilder.Entity("OfficeNova.Bestelportaal.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Omschrijving")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Prijs")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Voorraad")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Producten");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categorie = "Muizen",
                            Naam = "Logitech ERGO M575",
                            Omschrijving = "Ergonomische draadloze trackball muis",
                            Prijs = 49.99m,
                            Tags = "ergonomisch,draadloos,premium",
                            Voorraad = 25
                        },
                        new
                        {
                            Id = 2,
                            Categorie = "Muizen",
                            Naam = "Trust Yvi Draadloze Muis",
                            Omschrijving = "Goedkope draadloze muis voor flexplekken",
                            Prijs = 12.99m,
                            Tags = "goedkoop,draadloos,compact",
                            Voorraad = 100
                        },
                        new
                        {
                            Id = 3,
                            Categorie = "Muizen",
                            Naam = "Logitech MX Master 3S",
                            Omschrijving = "Premium draadloze muis voor professionals",
                            Prijs = 99.99m,
                            Tags = "premium,draadloos,populair",
                            Voorraad = 15
                        },
                        new
                        {
                            Id = 4,
                            Categorie = "Ergonomie",
                            Naam = "Ergonomische Polssteun",
                            Omschrijving = "Polssteun tegen polsklachten bij computerwerk",
                            Prijs = 19.99m,
                            Tags = "ergonomisch,thuiswerken",
                            Voorraad = 40
                        },
                        new
                        {
                            Id = 5,
                            Categorie = "Toetsenborden",
                            Naam = "Logitech K380 Toetsenbord",
                            Omschrijving = "Stil compact draadloos toetsenbord",
                            Prijs = 39.99m,
                            Tags = "stil,compact,draadloos",
                            Voorraad = 30
                        },
                        new
                        {
                            Id = 6,
                            Categorie = "Toetsenborden",
                            Naam = "Microsoft Surface Keyboard",
                            Omschrijving = "Premium draadloos toetsenbord",
                            Prijs = 89.99m,
                            Tags = "premium,draadloos",
                            Voorraad = 10
                        },
                        new
                        {
                            Id = 7,
                            Categorie = "Toetsenborden",
                            Naam = "Ergonomisch Toetsenbord Split",
                            Omschrijving = "Split-toetsenbord voor ergonomisch thuiswerken",
                            Prijs = 129.99m,
                            Tags = "ergonomisch,thuiswerken,premium",
                            Voorraad = 8
                        },
                        new
                        {
                            Id = 8,
                            Categorie = "Headsets",
                            Naam = "Jabra Evolve2 40 Headset",
                            Omschrijving = "Stille headset voor gedeelde werkplek",
                            Prijs = 119.99m,
                            Tags = "stil,premium,populair",
                            Voorraad = 20
                        },
                        new
                        {
                            Id = 9,
                            Categorie = "Headsets",
                            Naam = "Logitech Zone 300 Headset",
                            Omschrijving = "Goedkope headset voor thuiswerken",
                            Prijs = 49.99m,
                            Tags = "goedkoop,thuiswerken",
                            Voorraad = 35
                        },
                        new
                        {
                            Id = 10,
                            Categorie = "Facilitair",
                            Naam = "Duurzame Koffiebeker RVS",
                            Omschrijving = "Herbruikbare koffiebeker van gerecycled RVS",
                            Prijs = 14.99m,
                            Tags = "duurzaam,populair",
                            Voorraad = 60
                        },
                        new
                        {
                            Id = 11,
                            Categorie = "Facilitair",
                            Naam = "Bamboe Koffiebeker",
                            Omschrijving = "Duurzame koffiebeker van bamboe",
                            Prijs = 9.99m,
                            Tags = "duurzaam,goedkoop",
                            Voorraad = 80
                        },
                        new
                        {
                            Id = 12,
                            Categorie = "Laptopstandaards",
                            Naam = "Laptopstandaard Verstelbaar",
                            Omschrijving = "Verstelbare aluminium laptopstandaard",
                            Prijs = 34.99m,
                            Tags = "ergonomisch,thuiswerken",
                            Voorraad = 25
                        },
                        new
                        {
                            Id = 13,
                            Categorie = "Laptopstandaards",
                            Naam = "Laptopstandaard Compact",
                            Omschrijving = "Compacte laptopstandaard voor flexplekken",
                            Prijs = 19.99m,
                            Tags = "compact,goedkoop",
                            Voorraad = 45
                        },
                        new
                        {
                            Id = 14,
                            Categorie = "Bureaustoelen",
                            Naam = "Bureaustoel Ergo Pro",
                            Omschrijving = "Ergonomische bureaustoel met lumbaalsteun",
                            Prijs = 299.99m,
                            Tags = "ergonomisch,premium,thuiswerken",
                            Voorraad = 12
                        },
                        new
                        {
                            Id = 15,
                            Categorie = "Bureaustoelen",
                            Naam = "Bureaustoel Basic",
                            Omschrijving = "Eenvoudige bureaustoel voor kantoor",
                            Prijs = 99.99m,
                            Tags = "goedkoop",
                            Voorraad = 30
                        },
                        new
                        {
                            Id = 16,
                            Categorie = "Printerinkt",
                            Naam = "Printerinkt Zwart Compatible",
                            Omschrijving = "Goedkope compatible printerinkt zwart",
                            Prijs = 12.99m,
                            Tags = "goedkoop,populair",
                            Voorraad = 100
                        },
                        new
                        {
                            Id = 17,
                            Categorie = "Printerinkt",
                            Naam = "Printerinkt Kleur Origineel",
                            Omschrijving = "Originele printerinkt kleur",
                            Prijs = 34.99m,
                            Tags = "premium",
                            Voorraad = 50
                        },
                        new
                        {
                            Id = 18,
                            Categorie = "Papier",
                            Naam = "A4 Papier 80 gram",
                            Omschrijving = "A4 papier 80 gram, 500 vel",
                            Prijs = 4.99m,
                            Tags = "goedkoop,populair",
                            Voorraad = 200
                        },
                        new
                        {
                            Id = 19,
                            Categorie = "Papier",
                            Naam = "A4 Papier 90 gram",
                            Omschrijving = "A4 papier 90 gram, 500 vel",
                            Prijs = 6.99m,
                            Tags = "premium",
                            Voorraad = 150
                        },
                        new
                        {
                            Id = 20,
                            Categorie = "Pennen",
                            Naam = "Balpen Zwart 10-pack",
                            Omschrijving = "Balpennen zwart, 10 stuks",
                            Prijs = 3.99m,
                            Tags = "goedkoop,populair",
                            Voorraad = 300
                        },
                        new
                        {
                            Id = 21,
                            Categorie = "Pennen",
                            Naam = "Gelpen Blauw 5-pack",
                            Omschrijving = "Gelpennen blauw, 5 stuks",
                            Prijs = 5.99m,
                            Tags = "goedkoop",
                            Voorraad = 200
                        },
                        new
                        {
                            Id = 22,
                            Categorie = "Monitorarmen",
                            Naam = "Monitorarm Verstelbaar",
                            Omschrijving = "Verstelbare monitorarm voor ergonomisch werken",
                            Prijs = 79.99m,
                            Tags = "ergonomisch,premium",
                            Voorraad = 18
                        },
                        new
                        {
                            Id = 23,
                            Categorie = "IT Accessoires",
                            Naam = "USB-C Hub 7-in-1",
                            Omschrijving = "USB-C hub met HDMI, USB en SD",
                            Prijs = 39.99m,
                            Tags = "populair,compact",
                            Voorraad = 40
                        },
                        new
                        {
                            Id = 24,
                            Categorie = "IT Accessoires",
                            Naam = "Webcam Full HD",
                            Omschrijving = "Full HD webcam voor thuiswerken",
                            Prijs = 59.99m,
                            Tags = "thuiswerken,populair",
                            Voorraad = 25
                        },
                        new
                        {
                            Id = 25,
                            Categorie = "Thuiswerkpakketten",
                            Naam = "Thuiswerkpakket Starter",
                            Omschrijving = "Compleet thuiswerkpakket: toetsenbord, muis, headset, laptopstandaard",
                            Prijs = 149.99m,
                            Tags = "thuiswerken,populair,premium",
                            Voorraad = 20
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
